### ISSUE TITLE
Automated style checking

### ISSUE THREAD

**Issue by foolswood** [concert/libadiff#46]
Find a style checker to use for the C side of things, at the moment the "rules" (enforced by hand) are pretty PEP8 like.

**Comment by foolswood** [comment]
Probably worth having a play with 'indent'...

**Comment by foolswood** [comment]
Maybe something like: `indent -npsl -npcs -ce -brf -brs -bap -sob -i4` would do for a start.

**Comment by ch3pjw** [comment]
Agreed - the stuff you showed me the other day was pretty neat, and I much favour a parser/reformatted than the beautified alternative. Once the build system stuff has stabilised I'd like to get a travis job going, including at least checking the committed code...

**Comment by ch3pjw** [comment]
Moved to https://gitlab.com/concert/libadiff/issues/3
